version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.8

    working_directory: ~/repo
    
    steps:
      - checkout
      - run: npm run production-build
      - run: sudo npm run setup-link
      - run: amplify