version: 0.2
env:
  shell: bash
  variables:
    E2E_TEST_COVERAGE_DIR: node_v8_coverage
    CI: true
    CIRCLECI: true
    CLI_REGION: us-east-1
phases:
  build:
    commands:
      - source ./shared-scripts.sh && _amplifyGeneralConfigTests
      - echo "Build Status"
      - echo $PROJECT_NAME
      - echo $BRANCH_NAME
      - echo "CODEBUILD_WEBHOOK_TRIGGER=$CODEBUILD_WEBHOOK_TRIGGER CODEBUILD_BUILD_SUCCEEDING=$CODEBUILD_BUILD_SUCCEEDING"
artifacts:
  files:
    - "shared-scripts.sh"
